package com.ludot.database;

import com.ludot.model.Colour;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public final class GameResultRepository {

    private static final String URL = "jdbc:h2:tcp://localhost:9092/./ludotdb";

    private static final String USER = "sa";
    private static final String PASSWORD = "";

    private final String databaseUrl;

    public GameResultRepository() {
        this(URL);
    }

    // Allows an isolated database while retaining the application's TCP default.
    public GameResultRepository(String databaseUrl) {
        this.databaseUrl = databaseUrl;
        createTable();
    }

    private void createTable() {
        String sql = """
                CREATE TABLE IF NOT EXISTS game_results (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    winner VARCHAR(20) NOT NULL,
                    completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                )
                """;

        try (
                Connection connection = DriverManager.getConnection(databaseUrl, USER, PASSWORD);
                Statement statement = connection.createStatement()) {
            statement.execute(sql);

        } catch (SQLException e) {
            throw new IllegalStateException(
                    "Unable to initialise game results database",
                    e);
        }
    }

    public void saveWinner(Colour winner) {
        String sql = "INSERT INTO game_results (winner) VALUES (?)";

        try (
                Connection connection = DriverManager.getConnection(databaseUrl, USER, PASSWORD);
                PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, winner.name());
            statement.executeUpdate();

        } catch (SQLException e) {
            throw new IllegalStateException(
                    "Unable to save game winner",
                    e);
        }
    }
}
